#!/usr/bin/env python3
"""Apply sst_v0_8_16_patch_bundle + patch_canon.txt for v0.8.17.

Merge order (PATCH_MANIFEST.md):
1. SST-73 cleanup
2. Main canon T-foliation remark
3. Research-track Route-I source integration
4. SST-63 integration with SST-23/56
5. SST-64 v2 status note
6. SST-34 direct-line exclusion note
7. patch_canon.txt ropelength / trefoil-alpha convention block
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
CANON_ROOT = ROOT.parent
BUNDLE = CANON_ROOT / "sst_v0_8_16_patch_bundle"
SNIPPETS = BUNDLE / "snippets"

PAPERS = CANON_ROOT.parent / "papers"
SST73 = (
    PAPERS
    / "SST-73_A_Poisson-Type_Gravity_Program_from_Organized_Swirl_Transport"
    / "SST-73_A_Poisson-Type_Gravity_Program_from_Organized_Swirl_Transport.tex"
)
SST63 = (
    PAPERS
    / "SST-23-56-63_Vacuum_Dual_Medium"
    / "SST-63_Holograpic"
    / "SST-63_Holograpic.tex"
)
SST64 = PAPERS / "SST-64_Covariant" / "SST-64_v2.tex"
SST34 = PAPERS / "SST-34_Hydrogen-Gravity" / "SST-34_Hydrogen-Gravity.tex"

SST63_BIB = r"""
    \bibitem{Unruh1976}
    W.~G.~Unruh (1976),
    ``Notes on black-hole evaporation,''
    \emph{Physical Review D} \textbf{14}, 870--892.
    doi: \href{https://doi.org/10.1103/PhysRevD.14.870}{10.1103/PhysRevD.14.870}.

    \bibitem{Fetter2009}
    A.~L.~Fetter (2009),
    ``Rotating trapped Bose--Einstein condensates,''
    \emph{Reviews of Modern Physics} \textbf{81}, 647--691.
    doi: \href{https://doi.org/10.1103/RevModPhys.81.647}{10.1103/RevModPhys.81.647}.

    \bibitem{RiccaMoffatt1992}
    R.~L.~Ricca and H.~K.~Moffatt (1992),
    ``The helicity of a knotted vortex filament,''
    \emph{Topological Aspects of the Dynamics of Fluids and Plasmas},
    NATO ASI Series, Springer.
    doi/permalink: \href{https://doi.org/10.1007/978-94-017-3550-6_15}{10.1007/978-94-017-3550-6_15}.

    \end{thebibliography}"""


def _read_snippet(name: str) -> str:
    return (SNIPPETS / name).read_text(encoding="utf-8")


def _replace_once(text: str, old: str, new: str, label: str, *, strict: bool = True) -> str:
    if old in text:
        return text.replace(old, new, 1)
    if strict and new.split("\n", 1)[0].strip() not in text:
        raise SystemExit(f"missing anchor for {label}:\n{old[:160]}...")
    return text


def _indent_block(text: str, spaces: int = 8) -> str:
    prefix = " " * spaces
    return "\n".join(prefix + line if line else line for line in text.splitlines())


def apply_sst73() -> None:
    if not SST73.is_file():
        print(f"WARNING: SST-73 not found at {SST73}; skipped.")
        return
    text = SST73.read_text(encoding="utf-8")
    if "Candidate C is therefore retained as the most structural stress diagnostic" in text:
        print("SST-73 bundle patch already present.")
        return

    pairs = [
        (
            "                We therefore elevate Candidate C to the main proposal.",
            "                Candidate C is therefore retained as the most structural stress diagnostic,\n"
            "                but it is not elevated to an independent bulk monopole law unless supplemented by\n"
            "                a genuine scalar density, an explicit boundary source, or a singular-core\n"
            "                contribution.",
            "SST-73 Candidate C elevation",
        ),
        (
            "            This is the first complete statement of the gravity program:\n"
            "            \\begin{equation}\n"
            "                \\boxed{\n"
            "                    \\text{Gravity is the scalar response field generated by the spatial organization of organized swirl transport.}\n"
            "                }\n"
            "                \\label{eq:program-statement}\n"
            "            \\end{equation}",
            "            This is the corrected research-track statement of the local stress-response program:\n"
            "            \\begin{equation}\n"
            "                \\boxed{\n"
            "                    \\text{Stress organization supplies a local diagnostic; Newtonian gravity requires a monopole-bearing density or boundary source.}\n"
            "                }\n"
            "                \\label{eq:program-statement}\n"
            "            \\end{equation}",
            "SST-73 program statement",
        ),
        (
            "        Thus mass becomes an integrated measure of organized transport curvature/compression.",
            "        For smooth compact incompressible stress fields this integral vanishes by the no-monopole result above.  Equation~\\eqref{eq:Mg-tensor} should therefore be read as a boundary/singular-core diagnostic, not as a closed bulk mass law.  A nonzero Newtonian monopole requires a genuine scalar density source such as \\(\\rhoM=\\rhoE/c^2\\), or an explicitly modeled boundary source.",
            "SST-73 Mg-tensor",
        ),
        (
            "        \\paragraph{Why \\(\\mathcal{S}_C\\) is preferred.}\n"
            "            It depends on the spatial organization of coherent transport stress itself and naturally distinguishes trivial transport from transport whose geometry biases the surrounding medium.",
            "        \\paragraph{Why \\(\\mathcal{S}_C\\) is retained only as a diagnostic.}\n"
            "            It depends on the spatial organization of coherent transport stress itself and naturally distinguishes trivial transport from transport whose geometry biases the surrounding medium.  However, for smooth compact incompressible fields it is a double-divergence source with zero monopole.  It is therefore preferred only as a local stress/pressure diagnostic or boundary-source detector, not as the primary Newtonian mass law.",
            "SST-73 S_C diagnostic",
        ),
        (
            "        The gravity program derived here can be implemented numerically as follows.",
            "        The stress-diagnostic and density-source gravity program can be implemented numerically as follows.  The two branches must be tested separately so that the local stress channel is not confused with the monopole-bearing Poisson channel.",
            "SST-73 workflow intro",
        ),
        (
            "        \\subsection*{Step 3: build the source density}\n"
            "            Either compute the full tensorial source\n"
            "            \\begin{equation}\n"
            "                \\mathcal{S}_{\\grav}(\\mathbf{x})\n"
            "                =\n"
            "                \\lambda\\,\\partial_i\\partial_j \\Sigma_{ij}(\\mathbf{x}),\n"
            "                \\label{eq:workflow-S}\n"
            "            \\end{equation}\n"
            "            or use the axisymmetric approximation\n"
            "            \\begin{equation}\n"
            "                \\rho_{\\grav}^{(\\SST)}(r,z)=\\alpha_{\\grav}\\,\\nabla^2(\\rhoF u_\\theta^2).\n"
            "                \\label{eq:workflow-rhog}\n"
            "            \\end{equation}",
            "        \\subsection*{Step 3: build the source density}\n"
            "            Either compute the full tensorial diagnostic\n"
            "            \\begin{equation}\n"
            "                \\mathcal{S}_{\\mathrm{stress}}(\\mathbf{x})\n"
            "                =\n"
            "                \\lambda\\,\\partial_i\\partial_j \\Sigma_{ij}(\\mathbf{x}),\n"
            "                \\label{eq:workflow-S}\n"
            "            \\end{equation}\n"
            "            and verify its no-monopole behaviour for compact smooth fields, or compute a separate monopole-bearing density source.  For axisymmetric stress diagnostics one may use\n"
            "            \\begin{equation}\n"
            "                \\rho_{\\grav}^{(\\SST)}(r,z)=\\alpha_{\\grav}\\,\\nabla^2(\\rhoF u_\\theta^2).\n"
            "                \\label{eq:workflow-rhog}\n"
            "            \\end{equation}",
            "SST-73 workflow step 3",
        ),
    ]
    for old, new, label in pairs:
        text = _replace_once(text, old, new, label)
    SST73.write_text(text, encoding="utf-8")
    print("SST-73 bundle patch applied.")


def apply_main_canon(version: str) -> None:
    main = ROOT / f"v{version}" / f"SST_CANON-v{version}.tex"
    text = main.read_text(encoding="utf-8")
    if "eq:absolute_T_local_tau_layers" in text:
        print(f"Main canon T-foliation remark already present in v{version}.")
        return

    anchor = (
        "        Here $t_{\\infty}$ denotes the asymptotic laboratory time and $t_{\\mathrm{loc}}$ "
        "the effective proper time associated with a localized process in the medium. In SST, this factor "
        "is interpreted as a fluid-kinematic clock field rather than as a purely geometric spacetime postulate.\n\n"
        "    \\subsection{Carrier-local clocking and the turnover scale}"
    )
    insert = _read_snippet("canon_time_constraint_remark.tex").rstrip() + "\n\n"
    new = anchor.replace(
        "\n\n    \\subsection{Carrier-local clocking",
        "\n\n" + insert + "    \\subsection{Carrier-local clocking",
        1,
    )
    text = _replace_once(text, anchor, new, "main canon T-foliation")
    main.write_text(text, encoding="utf-8")
    print(f"Main canon T-foliation remark applied to v{version}.")


def apply_research_track(version: str) -> None:
    rt = ROOT / f"v{version}" / f"SST_CANON-v{version}-research-track.tex"
    text = rt.read_text(encoding="utf-8")
    if "eq:rt_63_23_56_thermo_route" in text:
        print(f"Route-I integration already present in v{version} research track.")
        return

    anchor = (
        "\\textbf{[RESEARCH TRACK]} This is the most promising route because it connects\n"
        "directly to horizon, boundary, and holographic SST sectors.\n\n"
        "\\paragraph{Route II: Sakharov induced gravity.}"
    )
    insert = _read_snippet("research_track_routeI_source_integration.tex").rstrip() + "\n\n"
    new = anchor.replace(
        "\n\n\\paragraph{Route II:",
        "\n\n\n" + insert + "\n\\paragraph{Route II:",
        1,
    )
    text = _replace_once(text, anchor, new, "research track Route I")
    rt.write_text(text, encoding="utf-8")
    print(f"Route-I source integration applied to v{version} research track.")


def apply_sst63() -> None:
    if not SST63.is_file():
        print(f"WARNING: SST-63 not found at {SST63}; skipped.")
        return
    text = SST63.read_text(encoding="utf-8")
    if "Integration with Dual-Vacuum and Topological-Superfluid Sectors" in text:
        print("SST-63 integration section already present.")
        return

    anchor = (
        "        constraint-dominated dynamics.\n\n"
        "        %==============================================================================\n"
        "    \\section{Clock Holography, Falsifiers, and Minimal Experiments}"
    )
    section = _read_snippet("sst63_23_56_integration_section.tex").rstrip() + "\n\n"
    new = anchor.replace(
        "\n\n        %=====",
        "\n\n" + section + "        %=====",
        1,
    )
    text = _replace_once(text, anchor, new, "SST-63 integration section")
    if "\\bibitem{Unruh1976}" not in text:
        text = _replace_once(
            text,
            "    \\end{thebibliography}",
            SST63_BIB,
            "SST-63 bibliography",
        )
    SST63.write_text(text, encoding="utf-8")
    print("SST-63 integration patch applied.")


def apply_sst64() -> None:
    if not SST64.is_file():
        print(f"WARNING: SST-64_v2 not found at {SST64}; skipped.")
        return
    text = SST64.read_text(encoding="utf-8")
    if "SST-corpus status note" in text:
        print("SST-64 status note already present.")
        return

    anchor = (
        "gravity, and other UV approaches.\n\n"
        "\\subsection{Outline}"
    )
    note = _read_snippet("sst64_status_note.tex").rstrip() + "\n\n"
    new = anchor.replace("\n\n\\subsection{Outline}", "\n\n\n" + note + "\\subsection{Outline}", 1)
    text = _replace_once(text, anchor, new, "SST-64 status note")
    SST64.write_text(text, encoding="utf-8")
    print("SST-64 status note applied.")


def apply_sst34() -> None:
    if not SST34.is_file():
        print(f"WARNING: SST-34 not found at {SST34}; skipped.")
        return
    text = SST34.read_text(encoding="utf-8")
    if "Permanent exclusion: direct-line gravity" in text:
        print("SST-34 direct-line exclusion already present.")
        return

    anchor = (
        "\\section{Canonical reinterpretation: source vs field}\n"
        "The knot/circulation content described in this document remains useful"
    )
    note = _read_snippet("sst34_direct_line_exclusion.tex").rstrip() + "\n\n"
    new = anchor.replace(
        "source vs field}\nThe knot",
        "source vs field}\n\n\n" + note + "The knot",
        1,
    )
    text = _replace_once(text, anchor, new, "SST-34 exclusion")
    SST34.write_text(text, encoding="utf-8")
    print("SST-34 direct-line exclusion applied.")


def apply_ropelength_block(version: str) -> None:
    patch_file = CANON_ROOT / "patch_canon.txt"
    main = ROOT / f"v{version}" / f"SST_CANON-v{version}.tex"
    text = main.read_text(encoding="utf-8")
    if "Ropelength representative and thickness-constrained ground state" in text:
        print(f"Ropelength block already present in v{version}.")
        return

    block = _indent_block(patch_file.read_text(encoding="utf-8").rstrip()) + "\n\n"
    anchor = "        \\subsection{Finite-cell $\\alpha$ coincidence and obstruction summary}"
    text = _replace_once(text, anchor, block + anchor, "patch_canon ropelength")
    main.write_text(text, encoding="utf-8")
    print(f"patch_canon.txt ropelength block applied to v{version}.")


def apply(version: str = "0.8.17") -> None:
    apply_sst73()
    apply_main_canon(version)
    apply_research_track(version)
    apply_sst63()
    apply_sst64()
    apply_sst34()
    apply_ropelength_block(version)


def main() -> None:
    version = sys.argv[1] if len(sys.argv) > 1 else "0.8.17"
    apply(version)


if __name__ == "__main__":
    main()
