#!/usr/bin/env python3
"""
Read fusion_manifest.json, extract bodies for each listed source, and write *_Fusion_master.tex per hub.
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PAPERS_ROOT = (SCRIPT_DIR / "..").resolve()
MANIFEST = SCRIPT_DIR / "fusion_manifest.json"
EXTRACT = SCRIPT_DIR / "extract_fusion_body.py"


def latex_escape_comment(s: str) -> str:
    return s.replace("%", "\\%")


def subimport_tex_fragment(subdir: str, main_tex: str) -> str:
    """Return filename of body fragment and LaTeX subimport line."""
    stem = Path(main_tex).stem
    body_name = f"_fusion_body__{stem}.tex"
    # import package expects directory with trailing slash
    d = subdir.replace("\\", "/").strip("/") + "/"
    return body_name, f"\\subimport{{{d}}}{{{body_name}}}"


HUB_EXTRA_LATEX = {
    "SST-32-44": r"""
\usepackage{tikz}
\usetikzlibrary{arrows.meta,positioning,calc,fit,decorations.pathmorphing,matrix,backgrounds}
\usepackage[most]{tcolorbox}
\usepackage{adjustbox}
\usepackage{amsopn}
%% Minimal RevTeX-like fragments used in SST-32/44 sources
\makeatletter
\providecommand{\affiliation}[1]{\par{\centering\small #1\par}}
%% RevTeX helper used in one \papertitle string (SST-32 long source)
\providecommand{\A}{ }
\makeatother
""",
    "SST-29-52": r"""
%% Springer Nature (sn-jnl) title/abstract shims + plots (SST-52)
\usepackage{xparse}
\usepackage{tikz}
\usepackage{pgfplots}
\usepackage{pgfplotstable}
\usepackage{caption}
\pgfplotsset{compat=newest}
\providecommand{\fnm}[1]{#1}
\providecommand{\sur}[1]{#1}
\providecommand{\orgname}[1]{#1}
\providecommand{\orgaddress}[1]{#1}
\providecommand{\city}[1]{#1}
\providecommand{\country}[1]{#1}
\providecommand{\email}[1]{\par{\centering\small\texttt{#1}\par}}
\RenewDocumentCommand{\author}{s o m}{\par\vspace{0.75em}{\centering#3\par}\vspace{0.5em}}
\RenewDocumentCommand{\affil}{s o m}{{\centering\small #3\par}\vspace{1em}}
\providecommand{\keywords}[1]{\paragraph*{\textbf{Keywords:}} #1\par}
""",
}

MASTER_PREAMBLE = r"""%% AUTO-GENERATED by papers/_tools/build_fusion_latex.py
%% Re-run: python papers/_tools/build_fusion_latex.py
\documentclass[11pt,a4paper]{report}
\usepackage[T1]{fontenc}
\usepackage[utf8]{inputenc}
\usepackage{lmodern}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb,amsfonts,amsthm,bm}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{physics}
\usepackage{siunitx}
\sisetup{per-mode=symbol,detect-weight=true,detect-family=true}
\usepackage{microtype}
\usepackage[hidelinks]{hyperref}
\usepackage{import}
%% Union preamble for heterogeneous subpapers; hub-specific bits follow fusion cover metadata.
\makeatletter
%% AMS/REVTeX-like \title[short]{long} (metadata only; short title ignored here)
\def\title{\@ifnextchar[{\@fusion@title@opt}{\@fusion@title@plain}}
\def\@fusion@title@opt[#1]#2{\gdef\@title{#2}}
\def\@fusion@title@plain#1{\gdef\@title{#1}}
\makeatother
\providecommand{\p}{\partial}
\providecommand{\affiliation}[1]{\par{\centering\small #1\par}}
\providecommand{\affil}[1]{\par{\centering\small #1\par}}
\DeclareUnicodeCharacter{21D2}{\ensuremath{\Rightarrow}}

\title{%TITLE%}
\author{Omar Iskandarani (fusion draft)}
\date{\today}

%HUB_EXTRA%

\begin{document}
\maketitle
\section*{About this fusion draft}
This is an automatically assembled fusion draft: multiple SST manuscripts concatenated as chapters.
It is intended for navigation and editing workflow, not as a final merged publication without manual cleanup.

\tableofcontents
\clearpage

"""


def build_hub(hub: dict, papers_root: Path, run_extract: bool) -> None:
    hub_dir = papers_root / hub["hub_dir"]
    if not hub_dir.is_dir():
        raise FileNotFoundError(hub_dir)

    sources = hub["sources"]
    chapters_tex = []

    for src in sources:
        subdir = src["subdir"]
        main_tex = src["main_tex"]
        chapter_title = src["chapter"]
        full_main = hub_dir / subdir / main_tex
        if not full_main.is_file():
            raise FileNotFoundError(full_main)

        if run_extract:
            cmd = [sys.executable, str(EXTRACT), str(full_main)]
            if src.get("include_filtered_preamble", True):
                cmd.append("--with-preamble")
            r = subprocess.run(
                cmd,
                cwd=str(SCRIPT_DIR),
                capture_output=True,
                text=True,
            )
            if r.returncode != 0:
                print(r.stderr or r.stdout, file=sys.stderr)
                raise RuntimeError(f"extract failed for {full_main}")

        body_name, sub_line = subimport_tex_fragment(subdir, main_tex)
        body_path = hub_dir / subdir / body_name
        if not body_path.is_file():
            raise FileNotFoundError(f"Missing body fragment (run with extract): {body_path}")

        chapters_tex.append(
            f"\\chapter{{{latex_escape_comment(chapter_title)}}}\n{sub_line}\n\\clearpage\n\n"
        )

    title = hub["title"]
    master_name = hub["master_tex"]
    hub_id = hub.get("id", "")
    extra = HUB_EXTRA_LATEX.get(hub_id, "")
    preamble = MASTER_PREAMBLE.replace("%HUB_EXTRA%", extra)
    content = preamble.replace("%TITLE%", latex_escape_comment(title)) + "".join(chapters_tex) + "\\end{document}\n"
    out_path = hub_dir / master_name
    out_path.write_text(content, encoding="utf-8")
    print(f"Wrote {out_path}")


def main() -> int:
    import argparse

    ap = argparse.ArgumentParser()
    ap.add_argument("--no-extract", action="store_true", help="Only write masters; assume bodies exist")
    args = ap.parse_args()

    data = json.loads(MANIFEST.read_text(encoding="utf-8"))
    root = (SCRIPT_DIR / data.get("papers_root", "..")).resolve()
    if root != PAPERS_ROOT:
        pass  # allow override
    root = PAPERS_ROOT

    for hub in data["hubs"]:
        build_hub(hub, root, run_extract=not args.no_extract)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
