#!/usr/bin/env python3
"""
Extract the document body (between \\begin{document} and \\end{document})
from a standalone LaTeX file and write a fragment suitable for \\subimport.

Default output: alongside the source, named _fusion_body__<stem>.tex
"""
from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

BEGIN_DOC = re.compile(r"\\begin\s*\{\s*document\s*\}(?:\s*\[[^\]]*\])?", re.DOTALL)

# Lines dropped from preamble when --with-preamble (packages belong in Fusion_master).
_SKIP_PREAMBLE_PREFIXES = (
    "\\documentclass",
    "\\usepackage",
    "\\hypersetup",
    "\\usetikzlibrary",
    "\\geometry",
    "\\sisetup",
    # Standalone metadata (belongs in Fusion_master, not chapter fragments)
    "\\title",
    "\\author",
    "\\date",
)


def filtered_preamble(text: str) -> str:
    """Keep macro/title/author lines; drop documentclass and package loads."""
    m = BEGIN_DOC.search(text)
    if not m:
        return ""
    pre = text[: m.start()]
    lines_out: list[str] = []
    for line in pre.splitlines():
        t = line.strip()
        if not t:
            lines_out.append("")
            continue
        if t.startswith("%"):
            continue
        if any(t.startswith(p) for p in _SKIP_PREAMBLE_PREFIXES):
            continue
        # Reduce duplicate-definition errors across fusion chapters
        if "\\renewcommand" not in line:
            line = re.sub(r"\\newcommand\b", r"\\providecommand", line)
        lines_out.append(line)
    return "\n".join(lines_out).rstrip() + "\n\n"


def extract_body(text: str) -> str:
    m = BEGIN_DOC.search(text)
    if not m:
        raise ValueError("No \\begin{document} found")
    start = m.end()
    end = text.rfind("\\end{document}")
    if end == -1:
        raise ValueError("No \\end{document} found")
    body = text[start:end].strip()
    return body


def default_body_path(source_tex: Path) -> Path:
    stem = source_tex.stem
    return source_tex.parent / f"_fusion_body__{stem}.tex"


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source_tex", type=Path, help="Path to full LaTeX file with preamble")
    ap.add_argument(
        "-o",
        "--output",
        type=Path,
        default=None,
        help="Output fragment path (default: alongside source, _fusion_body__<stem>.tex)",
    )
    ap.add_argument("--check", action="store_true", help="Only verify extraction; do not write")
    ap.add_argument(
        "--with-preamble",
        action="store_true",
        help="Prepend filtered preamble (macros/title) before body; needed for RevTeX-style sources",
    )
    args = ap.parse_args()

    src = args.source_tex.resolve()
    if not src.is_file():
        print(f"Not found: {src}", file=sys.stderr)
        return 1

    text = src.read_text(encoding="utf-8", errors="replace")
    try:
        body = extract_body(text)
    except ValueError as e:
        print(f"{src}: {e}", file=sys.stderr)
        return 2

    pre = filtered_preamble(text) if args.with_preamble else ""
    merged = pre + body if args.with_preamble else body

    out = args.output.resolve() if args.output else default_body_path(src)
    header = (
        "% Auto-generated by extract_fusion_body.py from:\n"
        f"%   {src.as_posix()}\n"
        "% Do not edit manually unless you accept regeneration overwrite.\n\n"
    )
    if args.with_preamble:
        header += "% with --with-preamble: filtered source preamble prepended\n\n"

    if args.check:
        print(f"OK {len(merged)} chars -> would write {out}")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(header + merged + "\n", encoding="utf-8")
    print(f"Wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
